### ISSUE TITLE
Feature missing!

### ISSUE THREAD

**Issue by bokrma** [debrajpaul/email-engine-core#1]
Hello!
as I noticed, I can't see the real-time syncing of changes when an email got moved from one mailbox to another or a new email is received or deleted
there should be handling for the update in real-time/near real-time with expecting that the system will have thousands of accounts

**Comment by debrajpaul** [comment]
Hello,

Thank you for your feedback and for pointing out the areas where real-time syncing of changes can be improved. I appreciate the opportunity to provide clarification and outline the steps I would take to ensure the system handles real-time updates efficiently, even with thousands of accounts.

Real-Time Synchronization
Current Implementation:
The current implementation is designed to fetch and store email data upon initial synchronization. However, it appears that real-time updates (such as when an email is moved, received, or deleted) are not being reflected immediately in the user interface.

Proposed Enhancements:
To address this, I propose the following enhancements to ensure real-time or near real-time updates are handled efficiently:

Webhooks Integration:

Outlook Webhooks: Utilize Outlook's webhooks to receive notifications about changes in the mailbox (e.g., new email, moved email, deleted email).

Implementation: Set up webhook endpoints to listen for these notifications and update the local database (Elasticsearch) accordingly.

Kafka for Real-Time Processing:

Asynchronous Processing: Use Kafka to handle real-time updates by publishing change events to Kafka topics. A consumer service can then process these events and update the local database.

Scalability: Kafka’s distributed nature ensures that the system can handle a high volume of events, making it suitable for thousands of accounts.

**Comment by bokrma** [comment]
yes there is one thing, that even the notification could be missed from outlook side,
means only subscribing to the webhooks will not make a full working solution
please research and check if you can find a combined solution to do the fetching near real time and insure the data is 100% as on the email server

**Comment by debrajpaul** [comment]
Hello,

Thank you for bringing this critical point to my attention. You are correct that relying solely on webhooks for real-time updates might not ensure complete data accuracy, as notifications can sometimes be missed. To address this, I propose a combined solution that leverages both webhooks for real-time updates and a periodic polling mechanism to ensure data consistency.

Periodic Polling for Data Consistency:

Scheduled Polling: Implement a periodic polling mechanism that runs at scheduled intervals to fetch and synchronize data from the email server.

 Full Sync: This polling will ensure that any missed updates from the webhooks are captured and synchronized, thereby ensuring data consistency.

So that you know- I have made the changes accordingly.
